[project]
name = "ohgiri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.56.0",
    "python-dotenv>=1.2.1",
    "slack-bolt>=1.27.0",
    "schedule>=1.2.2",
]
